// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABVHTQQZsE1jXmY8ksI82NIVQcF_pd8xg',
    appId: '1:175751455675:web:0802b6aac68685fcaeda9e',
    messagingSenderId: '175751455675',
    projectId: 'mehibaba-7fec5',
    authDomain: 'mehibaba-7fec5.firebaseapp.com',
    storageBucket: 'mehibaba-7fec5.appspot.com',
    measurementId: 'G-2TV4ZVWHXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD66pm54JChJbMNwGOLNzzzGpHRkbu591A',
    appId: '1:175751455675:android:ca3c1245b9bc6bc7aeda9e',
    messagingSenderId: '175751455675',
    projectId: 'mehibaba-7fec5',
    storageBucket: 'mehibaba-7fec5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNIDl4WEH1Ud7EjCEUvrN2OLZn7CQIns0',
    appId: '1:175751455675:ios:d05bb641af6ae4e4aeda9e',
    messagingSenderId: '175751455675',
    projectId: 'mehibaba-7fec5',
    storageBucket: 'mehibaba-7fec5.appspot.com',
    iosBundleId: 'com.divinetechs.dtliveapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNIDl4WEH1Ud7EjCEUvrN2OLZn7CQIns0',
    appId: '1:175751455675:ios:d05bb641af6ae4e4aeda9e',
    messagingSenderId: '175751455675',
    projectId: 'mehibaba-7fec5',
    storageBucket: 'mehibaba-7fec5.appspot.com',
    iosBundleId: 'com.divinetechs.dtliveapp',
  );
}
