import 'package:flutter/material.dart';

const appBgColor = Color(0xff0e171e);
const textColor = Colors.white;
const blackColor = Colors.black;
const black26 = Colors.black26;
var blugGreyDark = Colors.blueGrey[800];
const greyColor = Colors.grey;
const bluetext = Colors.blue;
var blueGrey500 = Colors.blueGrey[500];
const blueGreyColor = Colors.blueGrey;
var blueGrey900 = Colors.blueGrey[900];
var blueGrey600 = Colors.blueGrey[600];
var blueGrey300 = Colors.blueGrey[300];
var lightBlue800 = Colors.lightBlue[800];
const lightBlue = Colors.lightBlue;
var lightBlue200 = Colors.lightBlue[200];
const transParentColor = Colors.transparent;
const yellowColor = Colors.yellow;
var blueColor200 = Colors.blue[200];
const greyShade = Color.fromRGBO(0, 0, 0, 0.7);
const btnPrimaryblue = Color(0xff0e1c29);
const borderColor = Color(0xff24303c);
const textBlue = Color(0xff262e39);
